name: Canyon Ranch Safaris
favicon: null
layout_spectrum: 0.38348404760472476
typography_spectrum: 0.5563250181730837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7457681961823255
  lightness: 0.39207861316390336
  saturation: 0.5868363424669951
  rhythmicContrast: 0.11703526461496949
purpose: []
