name: Canyon Ranch Safaris
favicon: null
layout_spectrum: 0.38348404760472476
typography_spectrum: 0.5563250181730837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4b8db'
    - '#5b88b2'
    - '#040000'
    - '#4f3f3f'
    - '#2ec0fb'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
